---
# tasks file for keepalived
- name: Install Keepalived
  apt:
    name: keepalived
    state: present
  become: true

- name: Deploy Keepalived configuration file
  template:
    src: keepalived.conf.j2
    dest: "{{ keepalived_config_file }}"
    owner: root
    group: root
    mode: '0644'
  become: true
  notify: Restart Keepalived

