---
# handlers file for patroni
- name: Restart Patroni
  systemd:
    name: patroni
    state: restarted
  become: true


- name: Stop PostgreSQL
  systemd:
    name: postgresql
    state: stopped
  become: true    
