---
# tasks file for haproxy
- name: Install HAProxy
  apt:
    name: haproxy
    state: present
  become: true

- name: Deploy HAProxy configuration file
  template:
    src: haproxy.cfg.j2
    dest: "{{ haproxy_config_file }}"
    owner: root
    group: root
    mode: '0644'
  become: true
  notify: Restart HAProxy

